### ISSUE TITLE
Update RFC

### ISSUE THREAD

**Issue by bwaldbaum** [postalsys/postal-mime#29]
Hi @andris9 - Thank you for building postal-mime, it's very useful! In the readme.md it says that it complies with [RFC 822](https://www.rfc-editor.org/rfc/rfc822).  That is an old standard from 1982. The new standard is [RFC 5322](https://www.ietf.org/rfc/rfc5322.txt).

Can you update postal-mime to comply with 5322?  Or are you accepting pull requests if others want to make this update to the package?

Thank you,
Brett

**Comment by andris9** [comment]
It's rfc822 as in `message/rfc822` mime type. It does not change any time the standard gets an update.

**Comment by andris9** [comment]
Just to point out - by rfc822 I do not mean that postal-mime only supports the outdated RFC822 standard. It means that the email corresponds to the `message/rfc822` format. There is no such thing as `message/rfc5322`. All eml files are always `message/rfc822`.

**Comment by bakikucukcakiroglu** [comment]
Thanks @andris9 ! Very helpful explanation. 

I want to add my experience so that the ones having the same questions can find this thread with keywords. I'm using Gmail API and it returns RFC 2822 which is a successor of RFC822 but the parser just works fine with it. As you state, the raw message coming from Gmail API exactly matches with `message/rfc822` format
